// About Page Data — managed via Admin Tool
// Do not edit this file manually; use the Admin Tool settings instead.

var ABOUT_PHOTO  = 'assets/profile/profile.jpg'; // e.g. 'assets/profile/profile.jpg'
var ABOUT_SKILLS = 'Fotografie,Videografie,Webdesign,Branding,UI,UX';
