// Initial Project Data
const initialProjects = [
    {
        "id": 1,
        "number": "01",
        "bigNumber": "01",
        "title": "Ar\u00e9e",
        "category": "01",
        "shortDescription": "R\u00e4ume aus ungesehenen Blickwinkeln ",
        "description": "Die neu gestaltete Immobilie, welche von dem Architekturb\u00fcros Ar\u00e9e eingerichtet wurde, wurde in einer Fotoreihe abgebildet. Dabei lag der Fokus darauf, das Raumkonzept und die Einrichtung durch gezielte Perspektiven in Szene zu setzen. ",
        "image": "assets/projects/img_a0ad29d0.jpg",
        "gallery": [
            "assets/projects/img_65dc9081.jpg",
            "assets/projects/img_e7b532f7.jpg",
            "assets/projects/img_41b5afaf.jpg",
            "assets/projects/img_c31411f3.jpg",
            "assets/projects/img_6da432dd.jpg",
            "assets/projects/img_f9b1be2a.jpg",
            "assets/projects/img_414db4af.jpg",
            "assets/projects/img_ba252d2f.jpg",
            "assets/projects/img_0c2264d0.jpg",
            "assets/projects/img_d8aca1bf.jpg"
        ],
        "video": "",
        "icons": [],
        "companyLogo": ""
    },
    {
        "id": 2,
        "number": "02",
        "bigNumber": "02",
        "title": "Oliven\u00f6l",
        "category": "",
        "shortDescription": "",
        "description": "",
        "image": "",
        "gallery": [],
        "video": "",
        "icons": [],
        "companyLogo": ""
    },
    {
        "id": 3,
        "number": "03",
        "bigNumber": "03",
        "title": "Nussknacker",
        "category": "",
        "shortDescription": "",
        "description": "",
        "image": "",
        "gallery": [],
        "video": "",
        "icons": [],
        "companyLogo": ""
    },
    {
        "id": 4,
        "number": "04",
        "bigNumber": "04",
        "title": "Mercedes W123",
        "category": "",
        "shortDescription": "",
        "description": "",
        "image": "",
        "gallery": [],
        "video": "",
        "icons": [],
        "companyLogo": ""
    },
    {
        "id": 5,
        "number": "05",
        "bigNumber": "05",
        "title": "Julia",
        "category": "",
        "shortDescription": "",
        "description": "",
        "image": "",
        "gallery": [],
        "video": "",
        "icons": [],
        "companyLogo": ""
    },
    {
        "id": 6,
        "number": "06",
        "bigNumber": "06",
        "title": "Lange Theke",
        "category": "",
        "shortDescription": "",
        "description": "",
        "image": "",
        "gallery": [],
        "video": "",
        "icons": [],
        "companyLogo": ""
    },
    {
        "id": 7,
        "number": "07",
        "bigNumber": "07",
        "title": "24 Stunden Wandern",
        "category": "",
        "shortDescription": "",
        "description": "",
        "image": "",
        "gallery": [],
        "video": "",
        "icons": [],
        "companyLogo": ""
    },
    {
        "id": 8,
        "number": "08",
        "bigNumber": "08",
        "title": "HockenheimRing",
        "category": "",
        "shortDescription": "",
        "description": "",
        "image": "",
        "gallery": [],
        "video": "",
        "icons": [],
        "companyLogo": ""
    },
    {
        "id": 9,
        "number": "09",
        "bigNumber": "09",
        "title": "Nyhro",
        "category": "",
        "shortDescription": "",
        "description": "",
        "image": "",
        "gallery": [],
        "video": "",
        "icons": [],
        "companyLogo": ""
    }
];

window.initialProjects = initialProjects;
